"""Add agreed_privacy_policy fields

Revision ID: 406da50dd71d
Revises: 
Create Date: 2025-11-11 22:31:56.907209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406da50dd71d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agreed_privacy_policy', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('agreed_privacy_policy_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('agreed_privacy_policy_at')
        batch_op.drop_column('agreed_privacy_policy')

    # ### end Alembic commands ###
